export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const SAVE_FOLLOWERS = 'SAVE_FOLLOWERS';
export const SAVE_FOLLOWERS_FAILED = 'SAVE_FOLLOWERS_FAILED';
export const GET_PAGE = 'GET_PAGE';
export const MOVE_CURSOR = 'MOVE_CURSOR';
export const SHOW_ERROR = 'SHOW_ERROR';
export const SET_WORKING_PROCCESS = 'SET_WORKING_PROCCESS';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
